apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "application-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "application-service.name" . }}
    spec:
      containers:
      - name: application-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: {{ .Values.secrets.name }}
